// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApiKey = "api_keys"

// ApiKey mapped from table <api_keys>
type ApiKey struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	APIKey        string    `gorm:"column:api_key;type:varchar(128);not null;uniqueIndex:idx_api_keys_key,priority:1" json:"api_key"`
	Name          string    `gorm:"column:name;type:varchar(64);not null" json:"name"`
	CompanyID     int64     `gorm:"column:company_id;type:bigint;not null;index:idx_api_keys_company_id,priority:1" json:"company_id"`
	IsGlobal      bool      `gorm:"column:is_global;type:tinyint(1);not null" json:"is_global"`
	AllowedSkills *string   `gorm:"column:allowed_skills;type:json" json:"allowed_skills"`
	MaxConcurrent int64     `gorm:"column:max_concurrent;type:bigint;not null;default:3" json:"max_concurrent"`
	IsActive      bool      `gorm:"column:is_active;type:tinyint(1);not null;default:1" json:"is_active"`
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName ApiKey's table name
func (*ApiKey) TableName() string {
	return TableNameApiKey
}
