// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMemory = "memories"

// Memory mapped from table <memories>
type Memory struct {
	ID              int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	MemoryID        string         `gorm:"column:memory_id;type:varchar(36);not null;uniqueIndex:idx_memories_memory_id,priority:1" json:"memory_id"`
	CompanyID       int64          `gorm:"column:company_id;type:bigint;not null;uniqueIndex:uk_owner_key,priority:1;index:idx_memories_company_id,priority:1" json:"company_id"`
	UserID          int64          `gorm:"column:user_id;type:bigint;not null;uniqueIndex:uk_owner_key,priority:2;index:idx_memories_user_id,priority:1" json:"user_id"`
	Scope           string         `gorm:"column:scope;type:varchar(32);not null;uniqueIndex:uk_owner_key,priority:3;default:preference" json:"scope"`
	Topic           string         `gorm:"column:topic;type:varchar(64);not null;index:idx_memories_topic,priority:1" json:"topic"`
	KeyHint         string         `gorm:"column:key_hint;type:varchar(255);not null;uniqueIndex:uk_owner_key,priority:4" json:"key_hint"`
	Content         string         `gorm:"column:content;type:varchar(255);not null" json:"content"`
	Source          string         `gorm:"column:source;type:varchar(16);not null;index:idx_memories_source,priority:1;default:explicit" json:"source"`
	SourceSessionID *string        `gorm:"column:source_session_id;type:varchar(36)" json:"source_session_id"`
	SourceMessageID *string        `gorm:"column:source_message_id;type:varchar(36)" json:"source_message_id"`
	Pinned          bool           `gorm:"column:pinned;type:tinyint(1);not null" json:"pinned"`
	HitCount        int64          `gorm:"column:hit_count;type:bigint;not null" json:"hit_count"`
	LastUsedAt      *time.Time     `gorm:"column:last_used_at;type:datetime(3)" json:"last_used_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_memories_deleted_at,priority:1" json:"deleted_at"`
	CreatedAt       time.Time      `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName Memory's table name
func (*Memory) TableName() string {
	return TableNameMemory
}
