// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	MessageID   string    `gorm:"column:message_id;type:varchar(36);not null;uniqueIndex:idx_messages_message_id,priority:1" json:"message_id"`
	SessionID   string    `gorm:"column:session_id;type:varchar(36);not null;index:idx_messages_session_id,priority:1" json:"session_id"`
	Role        string    `gorm:"column:role;type:varchar(32);not null" json:"role"`
	Content     string    `gorm:"column:content;type:longtext;not null" json:"content"`
	Reasoning   *string   `gorm:"column:reasoning;type:longtext;comment:模型思考过程" json:"reasoning"` // 模型思考过程
	ToolCalls   *string   `gorm:"column:tool_calls;type:json" json:"tool_calls"`
	ToolCallID  *string   `gorm:"column:tool_call_id;type:varchar(64)" json:"tool_call_id"`
	Name        *string   `gorm:"column:name;type:varchar(128)" json:"name"`
	Attachments *string   `gorm:"column:attachments;type:json" json:"attachments"`
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
