// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSessionSkill = "session_skills"

// SessionSkill mapped from table <session_skills>
type SessionSkill struct {
	ID                  int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SessionID           string `gorm:"column:session_id;type:varchar(36);not null;uniqueIndex:uk_session_skill,priority:1;index:idx_session_skills_session_id,priority:1" json:"session_id"`
	SkillID             int64  `gorm:"column:skill_id;type:bigint;not null;uniqueIndex:uk_session_skill,priority:2;index:idx_session_skills_skill_id,priority:1" json:"skill_id"`
	PinnedVersionNumber *int64 `gorm:"column:pinned_version_number;type:bigint" json:"pinned_version_number"`
	Source              string `gorm:"column:source;type:varchar(16);not null;default:manual" json:"source"`
}

// TableName SessionSkill's table name
func (*SessionSkill) TableName() string {
	return TableNameSessionSkill
}
