// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSessionDigest = "session_digests"

// SessionDigest mapped from table <session_digests>
type SessionDigest struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SessionID       string    `gorm:"column:session_id;type:varchar(36);not null;index:idx_session_digests_session_id,priority:1" json:"session_id"`
	UptoMessageID   int64     `gorm:"column:upto_message_id;type:bigint;not null;index:idx_session_digests_upto_message_id,priority:1" json:"upto_message_id"`
	Content         string    `gorm:"column:content;type:longtext;not null" json:"content"`
	CoveredTokens   int64     `gorm:"column:covered_tokens;type:bigint;not null" json:"covered_tokens"`
	CoveredMessages int64     `gorm:"column:covered_messages;type:bigint;not null" json:"covered_messages"`
	CreatedAt       time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName SessionDigest's table name
func (*SessionDigest) TableName() string {
	return TableNameSessionDigest
}
