// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID                           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SessionID                    string    `gorm:"column:session_id;type:varchar(36);not null;uniqueIndex:idx_sessions_session_id,priority:1" json:"session_id"`
	CompanyID                    int64     `gorm:"column:company_id;type:bigint;not null;index:idx_sessions_company_id,priority:1" json:"company_id"`
	UserID                       int64     `gorm:"column:user_id;type:bigint;not null;index:idx_sessions_user_id,priority:1" json:"user_id"`
	Title                        string    `gorm:"column:title;type:varchar(255);not null;default:新会话" json:"title"`
	Model                        string    `gorm:"column:model;type:varchar(128);not null" json:"model"`
	SystemPrompt                 string    `gorm:"column:system_prompt;type:longtext;not null" json:"system_prompt"`
	AutoSkill                    bool      `gorm:"column:auto_skill;type:tinyint(1);not null;default:1" json:"auto_skill"`
	Interactive                  bool      `gorm:"column:interactive;type:tinyint(1);not null" json:"interactive"`
	APIKeyID                     *int64    `gorm:"column:api_key_id;type:bigint;index:idx_sessions_api_key_id,priority:1" json:"api_key_id"`
	LastContextTokens            int64     `gorm:"column:last_context_tokens;type:bigint;not null" json:"last_context_tokens"`
	MemoryExtractedUptoMessageID int64     `gorm:"column:memory_extracted_upto_message_id;type:bigint;not null" json:"memory_extracted_upto_message_id"`
	CreatedAt                    time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt                    time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
