// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSkillVersion = "skill_versions"

// SkillVersion mapped from table <skill_versions>
type SkillVersion struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SkillID       int64     `gorm:"column:skill_id;type:bigint;not null;index:idx_skill_versions_skill_id,priority:1" json:"skill_id"`
	VersionNumber int64     `gorm:"column:version_number;type:bigint;not null" json:"version_number"`
	Notes         string    `gorm:"column:notes;type:text;not null" json:"notes"`
	CreatedBy     int64     `gorm:"column:created_by;type:bigint;not null" json:"created_by"`
	CreatedByName string    `gorm:"column:created_by_name;type:varchar(64);not null" json:"created_by_name"`
	Source        string    `gorm:"column:source;type:varchar(16);not null;default:publish" json:"source"`
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName SkillVersion's table name
func (*SkillVersion) TableName() string {
	return TableNameSkillVersion
}
