// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSkillRun = "skill_runs"

// SkillRun mapped from table <skill_runs>
type SkillRun struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RunID       string     `gorm:"column:run_id;type:varchar(36);not null;uniqueIndex:idx_skill_runs_run_id,priority:1" json:"run_id"`
	SkillName   string     `gorm:"column:skill_name;type:varchar(128);not null;index:idx_skill_runs_skill_name,priority:1" json:"skill_name"`
	SkillID     *int64     `gorm:"column:skill_id;type:bigint;index:idx_skill_runs_skill_id,priority:1" json:"skill_id"`
	CompanyID   int64      `gorm:"column:company_id;type:bigint;not null;index:idx_skill_runs_company_id,priority:1" json:"company_id"`
	UserID      int64      `gorm:"column:user_id;type:bigint;not null;index:idx_skill_runs_user_id,priority:1" json:"user_id"`
	APIKeyID    *int64     `gorm:"column:api_key_id;type:bigint;index:idx_skill_runs_api_key_id,priority:1" json:"api_key_id"`
	SessionID   *string    `gorm:"column:session_id;type:varchar(36);index:idx_skill_runs_session_id,priority:1" json:"session_id"`
	Status      string     `gorm:"column:status;type:varchar(20);not null;index:idx_skill_runs_status,priority:1" json:"status"`
	Params      *string    `gorm:"column:params;type:json" json:"params"`
	Result      *string    `gorm:"column:result;type:json" json:"result"`
	Artifacts   *string    `gorm:"column:artifacts;type:json" json:"artifacts"`
	Progress    *string    `gorm:"column:progress;type:json" json:"progress"`
	Error       *string    `gorm:"column:error;type:text" json:"error"`
	StdoutTail  *string    `gorm:"column:stdout_tail;type:text" json:"stdout_tail"`
	StderrTail  *string    `gorm:"column:stderr_tail;type:text" json:"stderr_tail"`
	DurationMs  *int64     `gorm:"column:duration_ms;type:bigint" json:"duration_ms"`
	Attempt     int64      `gorm:"column:attempt;type:bigint;not null;default:1" json:"attempt"`
	MaxAttempts int64      `gorm:"column:max_attempts;type:bigint;not null;default:1" json:"max_attempts"`
	FailureKind *string    `gorm:"column:failure_kind;type:varchar(32)" json:"failure_kind"`
	NextRetryAt *time.Time `gorm:"column:next_retry_at;type:datetime(3)" json:"next_retry_at"`
	ExecContext *string    `gorm:"column:exec_context;type:json" json:"exec_context"`
	Attempts    *string    `gorm:"column:attempts;type:json" json:"attempts"`
	CreatedAt   time.Time  `gorm:"column:created_at;type:datetime(3);not null;index:idx_skill_runs_created_at,priority:1;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	StartedAt   *time.Time `gorm:"column:started_at;type:datetime(3)" json:"started_at"`
	FinishedAt  *time.Time `gorm:"column:finished_at;type:datetime(3)" json:"finished_at"`
}

// TableName SkillRun's table name
func (*SkillRun) TableName() string {
	return TableNameSkillRun
}
