// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSkill = "skills"

// Skill mapped from table <skills>
type Skill struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;type:varchar(128);not null;uniqueIndex:idx_skills_name,priority:1" json:"name"`
	Description  string    `gorm:"column:description;type:longtext;not null" json:"description"`
	DirName      string    `gorm:"column:dir_name;type:varchar(128);not null;uniqueIndex:idx_skills_dir_name,priority:1" json:"dir_name"`
	OwnerID      int64     `gorm:"column:owner_id;type:bigint;not null" json:"owner_id"`
	OwnerName    string    `gorm:"column:owner_name;type:varchar(64);not null" json:"owner_name"`
	Confidential bool      `gorm:"column:confidential;type:tinyint(1);not null" json:"confidential"`
	Model        *string   `gorm:"column:model;type:varchar(128)" json:"model"`
	Tags         *string   `gorm:"column:tags;type:json" json:"tags"`
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
