// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTokenUsage = "token_usages"

// TokenUsage mapped from table <token_usages>
type TokenUsage struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SessionID        string    `gorm:"column:session_id;type:varchar(36);not null;index:idx_token_usages_session_id,priority:1" json:"session_id"`
	CompanyID        int64     `gorm:"column:company_id;type:bigint;not null;index:idx_token_usages_company_id,priority:1" json:"company_id"`
	UserID           int64     `gorm:"column:user_id;type:bigint;not null;index:idx_token_usages_user_id,priority:1" json:"user_id"`
	Model            string    `gorm:"column:model;type:varchar(128);not null;index:idx_token_usages_model,priority:1" json:"model"`
	ProviderKey      string    `gorm:"column:provider_key;type:varchar(64);not null" json:"provider_key"`
	RoundIndex       int64     `gorm:"column:round_index;type:bigint;not null" json:"round_index"`
	Purpose          string    `gorm:"column:purpose;type:varchar(16);not null;index:idx_token_usages_purpose,priority:1;default:turn" json:"purpose"`
	PromptTokens     int64     `gorm:"column:prompt_tokens;type:bigint;not null" json:"prompt_tokens"`
	CompletionTokens int64     `gorm:"column:completion_tokens;type:bigint;not null" json:"completion_tokens"`
	CachedTokens     int64     `gorm:"column:cached_tokens;type:bigint;not null" json:"cached_tokens"`
	ReasoningTokens  int64     `gorm:"column:reasoning_tokens;type:bigint;not null" json:"reasoning_tokens"`
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime(3);not null;index:idx_token_usages_created_at,priority:1;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TokenUsage's table name
func (*TokenUsage) TableName() string {
	return TableNameTokenUsage
}
