// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newApiKey(db *gorm.DB, opts ...gen.DOOption) apiKey {
	_apiKey := apiKey{}

	_apiKey.apiKeyDo.UseDB(db, opts...)
	_apiKey.apiKeyDo.UseModel(&model.ApiKey{})

	tableName := _apiKey.apiKeyDo.TableName()
	_apiKey.ALL = field.NewAsterisk(tableName)
	_apiKey.ID = field.NewInt64(tableName, "id")
	_apiKey.APIKey = field.NewString(tableName, "api_key")
	_apiKey.Name = field.NewString(tableName, "name")
	_apiKey.CompanyID = field.NewInt64(tableName, "company_id")
	_apiKey.IsGlobal = field.NewBool(tableName, "is_global")
	_apiKey.AllowedSkills = field.NewString(tableName, "allowed_skills")
	_apiKey.MaxConcurrent = field.NewInt64(tableName, "max_concurrent")
	_apiKey.IsActive = field.NewBool(tableName, "is_active")
	_apiKey.CreatedAt = field.NewTime(tableName, "created_at")

	_apiKey.fillFieldMap()

	return _apiKey
}

type apiKey struct {
	apiKeyDo apiKeyDo

	ALL           field.Asterisk
	ID            field.Int64
	APIKey        field.String
	Name          field.String
	CompanyID     field.Int64
	IsGlobal      field.Bool
	AllowedSkills field.String
	MaxConcurrent field.Int64
	IsActive      field.Bool
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (a apiKey) Table(newTableName string) *apiKey {
	a.apiKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a apiKey) As(alias string) *apiKey {
	a.apiKeyDo.DO = *(a.apiKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *apiKey) updateTableName(table string) *apiKey {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.APIKey = field.NewString(table, "api_key")
	a.Name = field.NewString(table, "name")
	a.CompanyID = field.NewInt64(table, "company_id")
	a.IsGlobal = field.NewBool(table, "is_global")
	a.AllowedSkills = field.NewString(table, "allowed_skills")
	a.MaxConcurrent = field.NewInt64(table, "max_concurrent")
	a.IsActive = field.NewBool(table, "is_active")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *apiKey) WithContext(ctx context.Context) IApiKeyDo { return a.apiKeyDo.WithContext(ctx) }

func (a apiKey) TableName() string { return a.apiKeyDo.TableName() }

func (a apiKey) Alias() string { return a.apiKeyDo.Alias() }

func (a apiKey) Columns(cols ...field.Expr) gen.Columns { return a.apiKeyDo.Columns(cols...) }

func (a *apiKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *apiKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["api_key"] = a.APIKey
	a.fieldMap["name"] = a.Name
	a.fieldMap["company_id"] = a.CompanyID
	a.fieldMap["is_global"] = a.IsGlobal
	a.fieldMap["allowed_skills"] = a.AllowedSkills
	a.fieldMap["max_concurrent"] = a.MaxConcurrent
	a.fieldMap["is_active"] = a.IsActive
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a apiKey) clone(db *gorm.DB) apiKey {
	a.apiKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a apiKey) replaceDB(db *gorm.DB) apiKey {
	a.apiKeyDo.ReplaceDB(db)
	return a
}

type apiKeyDo struct{ gen.DO }

type IApiKeyDo interface {
	gen.SubQuery
	Debug() IApiKeyDo
	WithContext(ctx context.Context) IApiKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IApiKeyDo
	WriteDB() IApiKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IApiKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IApiKeyDo
	Not(conds ...gen.Condition) IApiKeyDo
	Or(conds ...gen.Condition) IApiKeyDo
	Select(conds ...field.Expr) IApiKeyDo
	Where(conds ...gen.Condition) IApiKeyDo
	Order(conds ...field.Expr) IApiKeyDo
	Distinct(cols ...field.Expr) IApiKeyDo
	Omit(cols ...field.Expr) IApiKeyDo
	Join(table schema.Tabler, on ...field.Expr) IApiKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo
	Group(cols ...field.Expr) IApiKeyDo
	Having(conds ...gen.Condition) IApiKeyDo
	Limit(limit int) IApiKeyDo
	Offset(offset int) IApiKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IApiKeyDo
	Unscoped() IApiKeyDo
	Create(values ...*model.ApiKey) error
	CreateInBatches(values []*model.ApiKey, batchSize int) error
	Save(values ...*model.ApiKey) error
	First() (*model.ApiKey, error)
	Take() (*model.ApiKey, error)
	Last() (*model.ApiKey, error)
	Find() ([]*model.ApiKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ApiKey, err error)
	FindInBatches(result *[]*model.ApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ApiKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IApiKeyDo
	Assign(attrs ...field.AssignExpr) IApiKeyDo
	Joins(fields ...field.RelationField) IApiKeyDo
	Preload(fields ...field.RelationField) IApiKeyDo
	FirstOrInit() (*model.ApiKey, error)
	FirstOrCreate() (*model.ApiKey, error)
	FindByPage(offset int, limit int) (result []*model.ApiKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IApiKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a apiKeyDo) Debug() IApiKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a apiKeyDo) WithContext(ctx context.Context) IApiKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a apiKeyDo) ReadDB() IApiKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a apiKeyDo) WriteDB() IApiKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a apiKeyDo) Session(config *gorm.Session) IApiKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a apiKeyDo) Clauses(conds ...clause.Expression) IApiKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a apiKeyDo) Returning(value interface{}, columns ...string) IApiKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a apiKeyDo) Not(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a apiKeyDo) Or(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a apiKeyDo) Select(conds ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a apiKeyDo) Where(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a apiKeyDo) Order(conds ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a apiKeyDo) Distinct(cols ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a apiKeyDo) Omit(cols ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a apiKeyDo) Join(table schema.Tabler, on ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a apiKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a apiKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a apiKeyDo) Group(cols ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a apiKeyDo) Having(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a apiKeyDo) Limit(limit int) IApiKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a apiKeyDo) Offset(offset int) IApiKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a apiKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IApiKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a apiKeyDo) Unscoped() IApiKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a apiKeyDo) Create(values ...*model.ApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a apiKeyDo) CreateInBatches(values []*model.ApiKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a apiKeyDo) Save(values ...*model.ApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a apiKeyDo) First() (*model.ApiKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApiKey), nil
	}
}

func (a apiKeyDo) Take() (*model.ApiKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApiKey), nil
	}
}

func (a apiKeyDo) Last() (*model.ApiKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApiKey), nil
	}
}

func (a apiKeyDo) Find() ([]*model.ApiKey, error) {
	result, err := a.DO.Find()
	return result.([]*model.ApiKey), err
}

func (a apiKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ApiKey, err error) {
	buf := make([]*model.ApiKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a apiKeyDo) FindInBatches(result *[]*model.ApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a apiKeyDo) Attrs(attrs ...field.AssignExpr) IApiKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a apiKeyDo) Assign(attrs ...field.AssignExpr) IApiKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a apiKeyDo) Joins(fields ...field.RelationField) IApiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a apiKeyDo) Preload(fields ...field.RelationField) IApiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a apiKeyDo) FirstOrInit() (*model.ApiKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApiKey), nil
	}
}

func (a apiKeyDo) FirstOrCreate() (*model.ApiKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApiKey), nil
	}
}

func (a apiKeyDo) FindByPage(offset int, limit int) (result []*model.ApiKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a apiKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a apiKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a apiKeyDo) Delete(models ...*model.ApiKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *apiKeyDo) withDO(do gen.Dao) *apiKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
