// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	ApiKey        *apiKey
	Memory        *memory
	Message       *message
	Session       *session
	SessionDigest *sessionDigest
	SessionSkill  *sessionSkill
	Skill         *skill
	SkillRun      *skillRun
	SkillVersion  *skillVersion
	TokenUsage    *tokenUsage
	UserInfo      *userInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ApiKey = &Q.ApiKey
	Memory = &Q.Memory
	Message = &Q.Message
	Session = &Q.Session
	SessionDigest = &Q.SessionDigest
	SessionSkill = &Q.SessionSkill
	Skill = &Q.Skill
	SkillRun = &Q.SkillRun
	SkillVersion = &Q.SkillVersion
	TokenUsage = &Q.TokenUsage
	UserInfo = &Q.UserInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		ApiKey:        newApiKey(db, opts...),
		Memory:        newMemory(db, opts...),
		Message:       newMessage(db, opts...),
		Session:       newSession(db, opts...),
		SessionDigest: newSessionDigest(db, opts...),
		SessionSkill:  newSessionSkill(db, opts...),
		Skill:         newSkill(db, opts...),
		SkillRun:      newSkillRun(db, opts...),
		SkillVersion:  newSkillVersion(db, opts...),
		TokenUsage:    newTokenUsage(db, opts...),
		UserInfo:      newUserInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ApiKey        apiKey
	Memory        memory
	Message       message
	Session       session
	SessionDigest sessionDigest
	SessionSkill  sessionSkill
	Skill         skill
	SkillRun      skillRun
	SkillVersion  skillVersion
	TokenUsage    tokenUsage
	UserInfo      userInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		ApiKey:        q.ApiKey.clone(db),
		Memory:        q.Memory.clone(db),
		Message:       q.Message.clone(db),
		Session:       q.Session.clone(db),
		SessionDigest: q.SessionDigest.clone(db),
		SessionSkill:  q.SessionSkill.clone(db),
		Skill:         q.Skill.clone(db),
		SkillRun:      q.SkillRun.clone(db),
		SkillVersion:  q.SkillVersion.clone(db),
		TokenUsage:    q.TokenUsage.clone(db),
		UserInfo:      q.UserInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		ApiKey:        q.ApiKey.replaceDB(db),
		Memory:        q.Memory.replaceDB(db),
		Message:       q.Message.replaceDB(db),
		Session:       q.Session.replaceDB(db),
		SessionDigest: q.SessionDigest.replaceDB(db),
		SessionSkill:  q.SessionSkill.replaceDB(db),
		Skill:         q.Skill.replaceDB(db),
		SkillRun:      q.SkillRun.replaceDB(db),
		SkillVersion:  q.SkillVersion.replaceDB(db),
		TokenUsage:    q.TokenUsage.replaceDB(db),
		UserInfo:      q.UserInfo.replaceDB(db),
	}
}

type queryCtx struct {
	ApiKey        IApiKeyDo
	Memory        IMemoryDo
	Message       IMessageDo
	Session       ISessionDo
	SessionDigest ISessionDigestDo
	SessionSkill  ISessionSkillDo
	Skill         ISkillDo
	SkillRun      ISkillRunDo
	SkillVersion  ISkillVersionDo
	TokenUsage    ITokenUsageDo
	UserInfo      IUserInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ApiKey:        q.ApiKey.WithContext(ctx),
		Memory:        q.Memory.WithContext(ctx),
		Message:       q.Message.WithContext(ctx),
		Session:       q.Session.WithContext(ctx),
		SessionDigest: q.SessionDigest.WithContext(ctx),
		SessionSkill:  q.SessionSkill.WithContext(ctx),
		Skill:         q.Skill.WithContext(ctx),
		SkillRun:      q.SkillRun.WithContext(ctx),
		SkillVersion:  q.SkillVersion.WithContext(ctx),
		TokenUsage:    q.TokenUsage.WithContext(ctx),
		UserInfo:      q.UserInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
