// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newMemory(db *gorm.DB, opts ...gen.DOOption) memory {
	_memory := memory{}

	_memory.memoryDo.UseDB(db, opts...)
	_memory.memoryDo.UseModel(&model.Memory{})

	tableName := _memory.memoryDo.TableName()
	_memory.ALL = field.NewAsterisk(tableName)
	_memory.ID = field.NewInt64(tableName, "id")
	_memory.MemoryID = field.NewString(tableName, "memory_id")
	_memory.CompanyID = field.NewInt64(tableName, "company_id")
	_memory.UserID = field.NewInt64(tableName, "user_id")
	_memory.Scope = field.NewString(tableName, "scope")
	_memory.Topic = field.NewString(tableName, "topic")
	_memory.KeyHint = field.NewString(tableName, "key_hint")
	_memory.Content = field.NewString(tableName, "content")
	_memory.Source = field.NewString(tableName, "source")
	_memory.SourceSessionID = field.NewString(tableName, "source_session_id")
	_memory.SourceMessageID = field.NewString(tableName, "source_message_id")
	_memory.Pinned = field.NewBool(tableName, "pinned")
	_memory.HitCount = field.NewInt64(tableName, "hit_count")
	_memory.LastUsedAt = field.NewTime(tableName, "last_used_at")
	_memory.DeletedAt = field.NewField(tableName, "deleted_at")
	_memory.CreatedAt = field.NewTime(tableName, "created_at")
	_memory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_memory.fillFieldMap()

	return _memory
}

type memory struct {
	memoryDo memoryDo

	ALL             field.Asterisk
	ID              field.Int64
	MemoryID        field.String
	CompanyID       field.Int64
	UserID          field.Int64
	Scope           field.String
	Topic           field.String
	KeyHint         field.String
	Content         field.String
	Source          field.String
	SourceSessionID field.String
	SourceMessageID field.String
	Pinned          field.Bool
	HitCount        field.Int64
	LastUsedAt      field.Time
	DeletedAt       field.Field
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (m memory) Table(newTableName string) *memory {
	m.memoryDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memory) As(alias string) *memory {
	m.memoryDo.DO = *(m.memoryDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memory) updateTableName(table string) *memory {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MemoryID = field.NewString(table, "memory_id")
	m.CompanyID = field.NewInt64(table, "company_id")
	m.UserID = field.NewInt64(table, "user_id")
	m.Scope = field.NewString(table, "scope")
	m.Topic = field.NewString(table, "topic")
	m.KeyHint = field.NewString(table, "key_hint")
	m.Content = field.NewString(table, "content")
	m.Source = field.NewString(table, "source")
	m.SourceSessionID = field.NewString(table, "source_session_id")
	m.SourceMessageID = field.NewString(table, "source_message_id")
	m.Pinned = field.NewBool(table, "pinned")
	m.HitCount = field.NewInt64(table, "hit_count")
	m.LastUsedAt = field.NewTime(table, "last_used_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *memory) WithContext(ctx context.Context) IMemoryDo { return m.memoryDo.WithContext(ctx) }

func (m memory) TableName() string { return m.memoryDo.TableName() }

func (m memory) Alias() string { return m.memoryDo.Alias() }

func (m memory) Columns(cols ...field.Expr) gen.Columns { return m.memoryDo.Columns(cols...) }

func (m *memory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memory) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 17)
	m.fieldMap["id"] = m.ID
	m.fieldMap["memory_id"] = m.MemoryID
	m.fieldMap["company_id"] = m.CompanyID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["scope"] = m.Scope
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["key_hint"] = m.KeyHint
	m.fieldMap["content"] = m.Content
	m.fieldMap["source"] = m.Source
	m.fieldMap["source_session_id"] = m.SourceSessionID
	m.fieldMap["source_message_id"] = m.SourceMessageID
	m.fieldMap["pinned"] = m.Pinned
	m.fieldMap["hit_count"] = m.HitCount
	m.fieldMap["last_used_at"] = m.LastUsedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m memory) clone(db *gorm.DB) memory {
	m.memoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memory) replaceDB(db *gorm.DB) memory {
	m.memoryDo.ReplaceDB(db)
	return m
}

type memoryDo struct{ gen.DO }

type IMemoryDo interface {
	gen.SubQuery
	Debug() IMemoryDo
	WithContext(ctx context.Context) IMemoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemoryDo
	WriteDB() IMemoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemoryDo
	Not(conds ...gen.Condition) IMemoryDo
	Or(conds ...gen.Condition) IMemoryDo
	Select(conds ...field.Expr) IMemoryDo
	Where(conds ...gen.Condition) IMemoryDo
	Order(conds ...field.Expr) IMemoryDo
	Distinct(cols ...field.Expr) IMemoryDo
	Omit(cols ...field.Expr) IMemoryDo
	Join(table schema.Tabler, on ...field.Expr) IMemoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemoryDo
	Group(cols ...field.Expr) IMemoryDo
	Having(conds ...gen.Condition) IMemoryDo
	Limit(limit int) IMemoryDo
	Offset(offset int) IMemoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryDo
	Unscoped() IMemoryDo
	Create(values ...*model.Memory) error
	CreateInBatches(values []*model.Memory, batchSize int) error
	Save(values ...*model.Memory) error
	First() (*model.Memory, error)
	Take() (*model.Memory, error)
	Last() (*model.Memory, error)
	Find() ([]*model.Memory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Memory, err error)
	FindInBatches(result *[]*model.Memory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Memory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemoryDo
	Assign(attrs ...field.AssignExpr) IMemoryDo
	Joins(fields ...field.RelationField) IMemoryDo
	Preload(fields ...field.RelationField) IMemoryDo
	FirstOrInit() (*model.Memory, error)
	FirstOrCreate() (*model.Memory, error)
	FindByPage(offset int, limit int) (result []*model.Memory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memoryDo) Debug() IMemoryDo {
	return m.withDO(m.DO.Debug())
}

func (m memoryDo) WithContext(ctx context.Context) IMemoryDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memoryDo) ReadDB() IMemoryDo {
	return m.Clauses(dbresolver.Read)
}

func (m memoryDo) WriteDB() IMemoryDo {
	return m.Clauses(dbresolver.Write)
}

func (m memoryDo) Session(config *gorm.Session) IMemoryDo {
	return m.withDO(m.DO.Session(config))
}

func (m memoryDo) Clauses(conds ...clause.Expression) IMemoryDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memoryDo) Returning(value interface{}, columns ...string) IMemoryDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memoryDo) Not(conds ...gen.Condition) IMemoryDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memoryDo) Or(conds ...gen.Condition) IMemoryDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memoryDo) Select(conds ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memoryDo) Where(conds ...gen.Condition) IMemoryDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memoryDo) Order(conds ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memoryDo) Distinct(cols ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memoryDo) Omit(cols ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memoryDo) Join(table schema.Tabler, on ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memoryDo) Group(cols ...field.Expr) IMemoryDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memoryDo) Having(conds ...gen.Condition) IMemoryDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memoryDo) Limit(limit int) IMemoryDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memoryDo) Offset(offset int) IMemoryDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memoryDo) Unscoped() IMemoryDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memoryDo) Create(values ...*model.Memory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memoryDo) CreateInBatches(values []*model.Memory, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memoryDo) Save(values ...*model.Memory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memoryDo) First() (*model.Memory, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Memory), nil
	}
}

func (m memoryDo) Take() (*model.Memory, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Memory), nil
	}
}

func (m memoryDo) Last() (*model.Memory, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Memory), nil
	}
}

func (m memoryDo) Find() ([]*model.Memory, error) {
	result, err := m.DO.Find()
	return result.([]*model.Memory), err
}

func (m memoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Memory, err error) {
	buf := make([]*model.Memory, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memoryDo) FindInBatches(result *[]*model.Memory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memoryDo) Attrs(attrs ...field.AssignExpr) IMemoryDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memoryDo) Assign(attrs ...field.AssignExpr) IMemoryDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memoryDo) Joins(fields ...field.RelationField) IMemoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memoryDo) Preload(fields ...field.RelationField) IMemoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memoryDo) FirstOrInit() (*model.Memory, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Memory), nil
	}
}

func (m memoryDo) FirstOrCreate() (*model.Memory, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Memory), nil
	}
}

func (m memoryDo) FindByPage(offset int, limit int) (result []*model.Memory, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memoryDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memoryDo) Delete(models ...*model.Memory) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memoryDo) withDO(do gen.Dao) *memoryDo {
	m.DO = *do.(*gen.DO)
	return m
}
