// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newSessionSkill(db *gorm.DB, opts ...gen.DOOption) sessionSkill {
	_sessionSkill := sessionSkill{}

	_sessionSkill.sessionSkillDo.UseDB(db, opts...)
	_sessionSkill.sessionSkillDo.UseModel(&model.SessionSkill{})

	tableName := _sessionSkill.sessionSkillDo.TableName()
	_sessionSkill.ALL = field.NewAsterisk(tableName)
	_sessionSkill.ID = field.NewInt64(tableName, "id")
	_sessionSkill.SessionID = field.NewString(tableName, "session_id")
	_sessionSkill.SkillID = field.NewInt64(tableName, "skill_id")
	_sessionSkill.PinnedVersionNumber = field.NewInt64(tableName, "pinned_version_number")
	_sessionSkill.Source = field.NewString(tableName, "source")

	_sessionSkill.fillFieldMap()

	return _sessionSkill
}

type sessionSkill struct {
	sessionSkillDo sessionSkillDo

	ALL                 field.Asterisk
	ID                  field.Int64
	SessionID           field.String
	SkillID             field.Int64
	PinnedVersionNumber field.Int64
	Source              field.String

	fieldMap map[string]field.Expr
}

func (s sessionSkill) Table(newTableName string) *sessionSkill {
	s.sessionSkillDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionSkill) As(alias string) *sessionSkill {
	s.sessionSkillDo.DO = *(s.sessionSkillDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionSkill) updateTableName(table string) *sessionSkill {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SessionID = field.NewString(table, "session_id")
	s.SkillID = field.NewInt64(table, "skill_id")
	s.PinnedVersionNumber = field.NewInt64(table, "pinned_version_number")
	s.Source = field.NewString(table, "source")

	s.fillFieldMap()

	return s
}

func (s *sessionSkill) WithContext(ctx context.Context) ISessionSkillDo {
	return s.sessionSkillDo.WithContext(ctx)
}

func (s sessionSkill) TableName() string { return s.sessionSkillDo.TableName() }

func (s sessionSkill) Alias() string { return s.sessionSkillDo.Alias() }

func (s sessionSkill) Columns(cols ...field.Expr) gen.Columns {
	return s.sessionSkillDo.Columns(cols...)
}

func (s *sessionSkill) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionSkill) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["skill_id"] = s.SkillID
	s.fieldMap["pinned_version_number"] = s.PinnedVersionNumber
	s.fieldMap["source"] = s.Source
}

func (s sessionSkill) clone(db *gorm.DB) sessionSkill {
	s.sessionSkillDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sessionSkill) replaceDB(db *gorm.DB) sessionSkill {
	s.sessionSkillDo.ReplaceDB(db)
	return s
}

type sessionSkillDo struct{ gen.DO }

type ISessionSkillDo interface {
	gen.SubQuery
	Debug() ISessionSkillDo
	WithContext(ctx context.Context) ISessionSkillDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionSkillDo
	WriteDB() ISessionSkillDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionSkillDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionSkillDo
	Not(conds ...gen.Condition) ISessionSkillDo
	Or(conds ...gen.Condition) ISessionSkillDo
	Select(conds ...field.Expr) ISessionSkillDo
	Where(conds ...gen.Condition) ISessionSkillDo
	Order(conds ...field.Expr) ISessionSkillDo
	Distinct(cols ...field.Expr) ISessionSkillDo
	Omit(cols ...field.Expr) ISessionSkillDo
	Join(table schema.Tabler, on ...field.Expr) ISessionSkillDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionSkillDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionSkillDo
	Group(cols ...field.Expr) ISessionSkillDo
	Having(conds ...gen.Condition) ISessionSkillDo
	Limit(limit int) ISessionSkillDo
	Offset(offset int) ISessionSkillDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionSkillDo
	Unscoped() ISessionSkillDo
	Create(values ...*model.SessionSkill) error
	CreateInBatches(values []*model.SessionSkill, batchSize int) error
	Save(values ...*model.SessionSkill) error
	First() (*model.SessionSkill, error)
	Take() (*model.SessionSkill, error)
	Last() (*model.SessionSkill, error)
	Find() ([]*model.SessionSkill, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SessionSkill, err error)
	FindInBatches(result *[]*model.SessionSkill, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SessionSkill) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionSkillDo
	Assign(attrs ...field.AssignExpr) ISessionSkillDo
	Joins(fields ...field.RelationField) ISessionSkillDo
	Preload(fields ...field.RelationField) ISessionSkillDo
	FirstOrInit() (*model.SessionSkill, error)
	FirstOrCreate() (*model.SessionSkill, error)
	FindByPage(offset int, limit int) (result []*model.SessionSkill, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionSkillDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sessionSkillDo) Debug() ISessionSkillDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionSkillDo) WithContext(ctx context.Context) ISessionSkillDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionSkillDo) ReadDB() ISessionSkillDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionSkillDo) WriteDB() ISessionSkillDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionSkillDo) Session(config *gorm.Session) ISessionSkillDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionSkillDo) Clauses(conds ...clause.Expression) ISessionSkillDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionSkillDo) Returning(value interface{}, columns ...string) ISessionSkillDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionSkillDo) Not(conds ...gen.Condition) ISessionSkillDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionSkillDo) Or(conds ...gen.Condition) ISessionSkillDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionSkillDo) Select(conds ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionSkillDo) Where(conds ...gen.Condition) ISessionSkillDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionSkillDo) Order(conds ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionSkillDo) Distinct(cols ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionSkillDo) Omit(cols ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionSkillDo) Join(table schema.Tabler, on ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionSkillDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionSkillDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionSkillDo) Group(cols ...field.Expr) ISessionSkillDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionSkillDo) Having(conds ...gen.Condition) ISessionSkillDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionSkillDo) Limit(limit int) ISessionSkillDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionSkillDo) Offset(offset int) ISessionSkillDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionSkillDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionSkillDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionSkillDo) Unscoped() ISessionSkillDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionSkillDo) Create(values ...*model.SessionSkill) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionSkillDo) CreateInBatches(values []*model.SessionSkill, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionSkillDo) Save(values ...*model.SessionSkill) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionSkillDo) First() (*model.SessionSkill, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionSkill), nil
	}
}

func (s sessionSkillDo) Take() (*model.SessionSkill, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionSkill), nil
	}
}

func (s sessionSkillDo) Last() (*model.SessionSkill, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionSkill), nil
	}
}

func (s sessionSkillDo) Find() ([]*model.SessionSkill, error) {
	result, err := s.DO.Find()
	return result.([]*model.SessionSkill), err
}

func (s sessionSkillDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SessionSkill, err error) {
	buf := make([]*model.SessionSkill, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionSkillDo) FindInBatches(result *[]*model.SessionSkill, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionSkillDo) Attrs(attrs ...field.AssignExpr) ISessionSkillDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionSkillDo) Assign(attrs ...field.AssignExpr) ISessionSkillDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionSkillDo) Joins(fields ...field.RelationField) ISessionSkillDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionSkillDo) Preload(fields ...field.RelationField) ISessionSkillDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionSkillDo) FirstOrInit() (*model.SessionSkill, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionSkill), nil
	}
}

func (s sessionSkillDo) FirstOrCreate() (*model.SessionSkill, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionSkill), nil
	}
}

func (s sessionSkillDo) FindByPage(offset int, limit int) (result []*model.SessionSkill, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionSkillDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionSkillDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionSkillDo) Delete(models ...*model.SessionSkill) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionSkillDo) withDO(do gen.Dao) *sessionSkillDo {
	s.DO = *do.(*gen.DO)
	return s
}
