// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newSessionDigest(db *gorm.DB, opts ...gen.DOOption) sessionDigest {
	_sessionDigest := sessionDigest{}

	_sessionDigest.sessionDigestDo.UseDB(db, opts...)
	_sessionDigest.sessionDigestDo.UseModel(&model.SessionDigest{})

	tableName := _sessionDigest.sessionDigestDo.TableName()
	_sessionDigest.ALL = field.NewAsterisk(tableName)
	_sessionDigest.ID = field.NewInt64(tableName, "id")
	_sessionDigest.SessionID = field.NewString(tableName, "session_id")
	_sessionDigest.UptoMessageID = field.NewInt64(tableName, "upto_message_id")
	_sessionDigest.Content = field.NewString(tableName, "content")
	_sessionDigest.CoveredTokens = field.NewInt64(tableName, "covered_tokens")
	_sessionDigest.CoveredMessages = field.NewInt64(tableName, "covered_messages")
	_sessionDigest.CreatedAt = field.NewTime(tableName, "created_at")

	_sessionDigest.fillFieldMap()

	return _sessionDigest
}

type sessionDigest struct {
	sessionDigestDo sessionDigestDo

	ALL             field.Asterisk
	ID              field.Int64
	SessionID       field.String
	UptoMessageID   field.Int64
	Content         field.String
	CoveredTokens   field.Int64
	CoveredMessages field.Int64
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (s sessionDigest) Table(newTableName string) *sessionDigest {
	s.sessionDigestDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionDigest) As(alias string) *sessionDigest {
	s.sessionDigestDo.DO = *(s.sessionDigestDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionDigest) updateTableName(table string) *sessionDigest {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SessionID = field.NewString(table, "session_id")
	s.UptoMessageID = field.NewInt64(table, "upto_message_id")
	s.Content = field.NewString(table, "content")
	s.CoveredTokens = field.NewInt64(table, "covered_tokens")
	s.CoveredMessages = field.NewInt64(table, "covered_messages")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sessionDigest) WithContext(ctx context.Context) ISessionDigestDo {
	return s.sessionDigestDo.WithContext(ctx)
}

func (s sessionDigest) TableName() string { return s.sessionDigestDo.TableName() }

func (s sessionDigest) Alias() string { return s.sessionDigestDo.Alias() }

func (s sessionDigest) Columns(cols ...field.Expr) gen.Columns {
	return s.sessionDigestDo.Columns(cols...)
}

func (s *sessionDigest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionDigest) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["upto_message_id"] = s.UptoMessageID
	s.fieldMap["content"] = s.Content
	s.fieldMap["covered_tokens"] = s.CoveredTokens
	s.fieldMap["covered_messages"] = s.CoveredMessages
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sessionDigest) clone(db *gorm.DB) sessionDigest {
	s.sessionDigestDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sessionDigest) replaceDB(db *gorm.DB) sessionDigest {
	s.sessionDigestDo.ReplaceDB(db)
	return s
}

type sessionDigestDo struct{ gen.DO }

type ISessionDigestDo interface {
	gen.SubQuery
	Debug() ISessionDigestDo
	WithContext(ctx context.Context) ISessionDigestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionDigestDo
	WriteDB() ISessionDigestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionDigestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionDigestDo
	Not(conds ...gen.Condition) ISessionDigestDo
	Or(conds ...gen.Condition) ISessionDigestDo
	Select(conds ...field.Expr) ISessionDigestDo
	Where(conds ...gen.Condition) ISessionDigestDo
	Order(conds ...field.Expr) ISessionDigestDo
	Distinct(cols ...field.Expr) ISessionDigestDo
	Omit(cols ...field.Expr) ISessionDigestDo
	Join(table schema.Tabler, on ...field.Expr) ISessionDigestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionDigestDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionDigestDo
	Group(cols ...field.Expr) ISessionDigestDo
	Having(conds ...gen.Condition) ISessionDigestDo
	Limit(limit int) ISessionDigestDo
	Offset(offset int) ISessionDigestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionDigestDo
	Unscoped() ISessionDigestDo
	Create(values ...*model.SessionDigest) error
	CreateInBatches(values []*model.SessionDigest, batchSize int) error
	Save(values ...*model.SessionDigest) error
	First() (*model.SessionDigest, error)
	Take() (*model.SessionDigest, error)
	Last() (*model.SessionDigest, error)
	Find() ([]*model.SessionDigest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SessionDigest, err error)
	FindInBatches(result *[]*model.SessionDigest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SessionDigest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionDigestDo
	Assign(attrs ...field.AssignExpr) ISessionDigestDo
	Joins(fields ...field.RelationField) ISessionDigestDo
	Preload(fields ...field.RelationField) ISessionDigestDo
	FirstOrInit() (*model.SessionDigest, error)
	FirstOrCreate() (*model.SessionDigest, error)
	FindByPage(offset int, limit int) (result []*model.SessionDigest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionDigestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sessionDigestDo) Debug() ISessionDigestDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionDigestDo) WithContext(ctx context.Context) ISessionDigestDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionDigestDo) ReadDB() ISessionDigestDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionDigestDo) WriteDB() ISessionDigestDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionDigestDo) Session(config *gorm.Session) ISessionDigestDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionDigestDo) Clauses(conds ...clause.Expression) ISessionDigestDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionDigestDo) Returning(value interface{}, columns ...string) ISessionDigestDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionDigestDo) Not(conds ...gen.Condition) ISessionDigestDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionDigestDo) Or(conds ...gen.Condition) ISessionDigestDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionDigestDo) Select(conds ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionDigestDo) Where(conds ...gen.Condition) ISessionDigestDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionDigestDo) Order(conds ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionDigestDo) Distinct(cols ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionDigestDo) Omit(cols ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionDigestDo) Join(table schema.Tabler, on ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionDigestDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionDigestDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionDigestDo) Group(cols ...field.Expr) ISessionDigestDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionDigestDo) Having(conds ...gen.Condition) ISessionDigestDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionDigestDo) Limit(limit int) ISessionDigestDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionDigestDo) Offset(offset int) ISessionDigestDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionDigestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionDigestDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionDigestDo) Unscoped() ISessionDigestDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionDigestDo) Create(values ...*model.SessionDigest) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionDigestDo) CreateInBatches(values []*model.SessionDigest, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionDigestDo) Save(values ...*model.SessionDigest) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionDigestDo) First() (*model.SessionDigest, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionDigest), nil
	}
}

func (s sessionDigestDo) Take() (*model.SessionDigest, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionDigest), nil
	}
}

func (s sessionDigestDo) Last() (*model.SessionDigest, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionDigest), nil
	}
}

func (s sessionDigestDo) Find() ([]*model.SessionDigest, error) {
	result, err := s.DO.Find()
	return result.([]*model.SessionDigest), err
}

func (s sessionDigestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SessionDigest, err error) {
	buf := make([]*model.SessionDigest, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionDigestDo) FindInBatches(result *[]*model.SessionDigest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionDigestDo) Attrs(attrs ...field.AssignExpr) ISessionDigestDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionDigestDo) Assign(attrs ...field.AssignExpr) ISessionDigestDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionDigestDo) Joins(fields ...field.RelationField) ISessionDigestDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionDigestDo) Preload(fields ...field.RelationField) ISessionDigestDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionDigestDo) FirstOrInit() (*model.SessionDigest, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionDigest), nil
	}
}

func (s sessionDigestDo) FirstOrCreate() (*model.SessionDigest, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionDigest), nil
	}
}

func (s sessionDigestDo) FindByPage(offset int, limit int) (result []*model.SessionDigest, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionDigestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionDigestDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionDigestDo) Delete(models ...*model.SessionDigest) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionDigestDo) withDO(do gen.Dao) *sessionDigestDo {
	s.DO = *do.(*gen.DO)
	return s
}
