// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newSkillVersion(db *gorm.DB, opts ...gen.DOOption) skillVersion {
	_skillVersion := skillVersion{}

	_skillVersion.skillVersionDo.UseDB(db, opts...)
	_skillVersion.skillVersionDo.UseModel(&model.SkillVersion{})

	tableName := _skillVersion.skillVersionDo.TableName()
	_skillVersion.ALL = field.NewAsterisk(tableName)
	_skillVersion.ID = field.NewInt64(tableName, "id")
	_skillVersion.SkillID = field.NewInt64(tableName, "skill_id")
	_skillVersion.VersionNumber = field.NewInt64(tableName, "version_number")
	_skillVersion.Notes = field.NewString(tableName, "notes")
	_skillVersion.CreatedBy = field.NewInt64(tableName, "created_by")
	_skillVersion.CreatedByName = field.NewString(tableName, "created_by_name")
	_skillVersion.Source = field.NewString(tableName, "source")
	_skillVersion.CreatedAt = field.NewTime(tableName, "created_at")

	_skillVersion.fillFieldMap()

	return _skillVersion
}

type skillVersion struct {
	skillVersionDo skillVersionDo

	ALL           field.Asterisk
	ID            field.Int64
	SkillID       field.Int64
	VersionNumber field.Int64
	Notes         field.String
	CreatedBy     field.Int64
	CreatedByName field.String
	Source        field.String
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s skillVersion) Table(newTableName string) *skillVersion {
	s.skillVersionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skillVersion) As(alias string) *skillVersion {
	s.skillVersionDo.DO = *(s.skillVersionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skillVersion) updateTableName(table string) *skillVersion {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SkillID = field.NewInt64(table, "skill_id")
	s.VersionNumber = field.NewInt64(table, "version_number")
	s.Notes = field.NewString(table, "notes")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.CreatedByName = field.NewString(table, "created_by_name")
	s.Source = field.NewString(table, "source")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *skillVersion) WithContext(ctx context.Context) ISkillVersionDo {
	return s.skillVersionDo.WithContext(ctx)
}

func (s skillVersion) TableName() string { return s.skillVersionDo.TableName() }

func (s skillVersion) Alias() string { return s.skillVersionDo.Alias() }

func (s skillVersion) Columns(cols ...field.Expr) gen.Columns {
	return s.skillVersionDo.Columns(cols...)
}

func (s *skillVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skillVersion) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["skill_id"] = s.SkillID
	s.fieldMap["version_number"] = s.VersionNumber
	s.fieldMap["notes"] = s.Notes
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["created_by_name"] = s.CreatedByName
	s.fieldMap["source"] = s.Source
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s skillVersion) clone(db *gorm.DB) skillVersion {
	s.skillVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skillVersion) replaceDB(db *gorm.DB) skillVersion {
	s.skillVersionDo.ReplaceDB(db)
	return s
}

type skillVersionDo struct{ gen.DO }

type ISkillVersionDo interface {
	gen.SubQuery
	Debug() ISkillVersionDo
	WithContext(ctx context.Context) ISkillVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISkillVersionDo
	WriteDB() ISkillVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISkillVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISkillVersionDo
	Not(conds ...gen.Condition) ISkillVersionDo
	Or(conds ...gen.Condition) ISkillVersionDo
	Select(conds ...field.Expr) ISkillVersionDo
	Where(conds ...gen.Condition) ISkillVersionDo
	Order(conds ...field.Expr) ISkillVersionDo
	Distinct(cols ...field.Expr) ISkillVersionDo
	Omit(cols ...field.Expr) ISkillVersionDo
	Join(table schema.Tabler, on ...field.Expr) ISkillVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISkillVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISkillVersionDo
	Group(cols ...field.Expr) ISkillVersionDo
	Having(conds ...gen.Condition) ISkillVersionDo
	Limit(limit int) ISkillVersionDo
	Offset(offset int) ISkillVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISkillVersionDo
	Unscoped() ISkillVersionDo
	Create(values ...*model.SkillVersion) error
	CreateInBatches(values []*model.SkillVersion, batchSize int) error
	Save(values ...*model.SkillVersion) error
	First() (*model.SkillVersion, error)
	Take() (*model.SkillVersion, error)
	Last() (*model.SkillVersion, error)
	Find() ([]*model.SkillVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkillVersion, err error)
	FindInBatches(result *[]*model.SkillVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SkillVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISkillVersionDo
	Assign(attrs ...field.AssignExpr) ISkillVersionDo
	Joins(fields ...field.RelationField) ISkillVersionDo
	Preload(fields ...field.RelationField) ISkillVersionDo
	FirstOrInit() (*model.SkillVersion, error)
	FirstOrCreate() (*model.SkillVersion, error)
	FindByPage(offset int, limit int) (result []*model.SkillVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISkillVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s skillVersionDo) Debug() ISkillVersionDo {
	return s.withDO(s.DO.Debug())
}

func (s skillVersionDo) WithContext(ctx context.Context) ISkillVersionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skillVersionDo) ReadDB() ISkillVersionDo {
	return s.Clauses(dbresolver.Read)
}

func (s skillVersionDo) WriteDB() ISkillVersionDo {
	return s.Clauses(dbresolver.Write)
}

func (s skillVersionDo) Session(config *gorm.Session) ISkillVersionDo {
	return s.withDO(s.DO.Session(config))
}

func (s skillVersionDo) Clauses(conds ...clause.Expression) ISkillVersionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skillVersionDo) Returning(value interface{}, columns ...string) ISkillVersionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skillVersionDo) Not(conds ...gen.Condition) ISkillVersionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s skillVersionDo) Or(conds ...gen.Condition) ISkillVersionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s skillVersionDo) Select(conds ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s skillVersionDo) Where(conds ...gen.Condition) ISkillVersionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s skillVersionDo) Order(conds ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s skillVersionDo) Distinct(cols ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skillVersionDo) Omit(cols ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skillVersionDo) Join(table schema.Tabler, on ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skillVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skillVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skillVersionDo) Group(cols ...field.Expr) ISkillVersionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s skillVersionDo) Having(conds ...gen.Condition) ISkillVersionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s skillVersionDo) Limit(limit int) ISkillVersionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s skillVersionDo) Offset(offset int) ISkillVersionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s skillVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISkillVersionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skillVersionDo) Unscoped() ISkillVersionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s skillVersionDo) Create(values ...*model.SkillVersion) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skillVersionDo) CreateInBatches(values []*model.SkillVersion, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skillVersionDo) Save(values ...*model.SkillVersion) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skillVersionDo) First() (*model.SkillVersion, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillVersion), nil
	}
}

func (s skillVersionDo) Take() (*model.SkillVersion, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillVersion), nil
	}
}

func (s skillVersionDo) Last() (*model.SkillVersion, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillVersion), nil
	}
}

func (s skillVersionDo) Find() ([]*model.SkillVersion, error) {
	result, err := s.DO.Find()
	return result.([]*model.SkillVersion), err
}

func (s skillVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkillVersion, err error) {
	buf := make([]*model.SkillVersion, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skillVersionDo) FindInBatches(result *[]*model.SkillVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skillVersionDo) Attrs(attrs ...field.AssignExpr) ISkillVersionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skillVersionDo) Assign(attrs ...field.AssignExpr) ISkillVersionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skillVersionDo) Joins(fields ...field.RelationField) ISkillVersionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skillVersionDo) Preload(fields ...field.RelationField) ISkillVersionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skillVersionDo) FirstOrInit() (*model.SkillVersion, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillVersion), nil
	}
}

func (s skillVersionDo) FirstOrCreate() (*model.SkillVersion, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillVersion), nil
	}
}

func (s skillVersionDo) FindByPage(offset int, limit int) (result []*model.SkillVersion, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skillVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skillVersionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skillVersionDo) Delete(models ...*model.SkillVersion) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skillVersionDo) withDO(do gen.Dao) *skillVersionDo {
	s.DO = *do.(*gen.DO)
	return s
}
