// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newSkillRun(db *gorm.DB, opts ...gen.DOOption) skillRun {
	_skillRun := skillRun{}

	_skillRun.skillRunDo.UseDB(db, opts...)
	_skillRun.skillRunDo.UseModel(&model.SkillRun{})

	tableName := _skillRun.skillRunDo.TableName()
	_skillRun.ALL = field.NewAsterisk(tableName)
	_skillRun.ID = field.NewInt64(tableName, "id")
	_skillRun.RunID = field.NewString(tableName, "run_id")
	_skillRun.SkillName = field.NewString(tableName, "skill_name")
	_skillRun.SkillID = field.NewInt64(tableName, "skill_id")
	_skillRun.CompanyID = field.NewInt64(tableName, "company_id")
	_skillRun.UserID = field.NewInt64(tableName, "user_id")
	_skillRun.APIKeyID = field.NewInt64(tableName, "api_key_id")
	_skillRun.SessionID = field.NewString(tableName, "session_id")
	_skillRun.Status = field.NewString(tableName, "status")
	_skillRun.Params = field.NewString(tableName, "params")
	_skillRun.Result = field.NewString(tableName, "result")
	_skillRun.Artifacts = field.NewString(tableName, "artifacts")
	_skillRun.Progress = field.NewString(tableName, "progress")
	_skillRun.Error = field.NewString(tableName, "error")
	_skillRun.StdoutTail = field.NewString(tableName, "stdout_tail")
	_skillRun.StderrTail = field.NewString(tableName, "stderr_tail")
	_skillRun.DurationMs = field.NewInt64(tableName, "duration_ms")
	_skillRun.Attempt = field.NewInt64(tableName, "attempt")
	_skillRun.MaxAttempts = field.NewInt64(tableName, "max_attempts")
	_skillRun.FailureKind = field.NewString(tableName, "failure_kind")
	_skillRun.NextRetryAt = field.NewTime(tableName, "next_retry_at")
	_skillRun.ExecContext = field.NewString(tableName, "exec_context")
	_skillRun.Attempts = field.NewString(tableName, "attempts")
	_skillRun.CreatedAt = field.NewTime(tableName, "created_at")
	_skillRun.StartedAt = field.NewTime(tableName, "started_at")
	_skillRun.FinishedAt = field.NewTime(tableName, "finished_at")

	_skillRun.fillFieldMap()

	return _skillRun
}

type skillRun struct {
	skillRunDo skillRunDo

	ALL         field.Asterisk
	ID          field.Int64
	RunID       field.String
	SkillName   field.String
	SkillID     field.Int64
	CompanyID   field.Int64
	UserID      field.Int64
	APIKeyID    field.Int64
	SessionID   field.String
	Status      field.String
	Params      field.String
	Result      field.String
	Artifacts   field.String
	Progress    field.String
	Error       field.String
	StdoutTail  field.String
	StderrTail  field.String
	DurationMs  field.Int64
	Attempt     field.Int64
	MaxAttempts field.Int64
	FailureKind field.String
	NextRetryAt field.Time
	ExecContext field.String
	Attempts    field.String
	CreatedAt   field.Time
	StartedAt   field.Time
	FinishedAt  field.Time

	fieldMap map[string]field.Expr
}

func (s skillRun) Table(newTableName string) *skillRun {
	s.skillRunDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skillRun) As(alias string) *skillRun {
	s.skillRunDo.DO = *(s.skillRunDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skillRun) updateTableName(table string) *skillRun {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.RunID = field.NewString(table, "run_id")
	s.SkillName = field.NewString(table, "skill_name")
	s.SkillID = field.NewInt64(table, "skill_id")
	s.CompanyID = field.NewInt64(table, "company_id")
	s.UserID = field.NewInt64(table, "user_id")
	s.APIKeyID = field.NewInt64(table, "api_key_id")
	s.SessionID = field.NewString(table, "session_id")
	s.Status = field.NewString(table, "status")
	s.Params = field.NewString(table, "params")
	s.Result = field.NewString(table, "result")
	s.Artifacts = field.NewString(table, "artifacts")
	s.Progress = field.NewString(table, "progress")
	s.Error = field.NewString(table, "error")
	s.StdoutTail = field.NewString(table, "stdout_tail")
	s.StderrTail = field.NewString(table, "stderr_tail")
	s.DurationMs = field.NewInt64(table, "duration_ms")
	s.Attempt = field.NewInt64(table, "attempt")
	s.MaxAttempts = field.NewInt64(table, "max_attempts")
	s.FailureKind = field.NewString(table, "failure_kind")
	s.NextRetryAt = field.NewTime(table, "next_retry_at")
	s.ExecContext = field.NewString(table, "exec_context")
	s.Attempts = field.NewString(table, "attempts")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.StartedAt = field.NewTime(table, "started_at")
	s.FinishedAt = field.NewTime(table, "finished_at")

	s.fillFieldMap()

	return s
}

func (s *skillRun) WithContext(ctx context.Context) ISkillRunDo { return s.skillRunDo.WithContext(ctx) }

func (s skillRun) TableName() string { return s.skillRunDo.TableName() }

func (s skillRun) Alias() string { return s.skillRunDo.Alias() }

func (s skillRun) Columns(cols ...field.Expr) gen.Columns { return s.skillRunDo.Columns(cols...) }

func (s *skillRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skillRun) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 26)
	s.fieldMap["id"] = s.ID
	s.fieldMap["run_id"] = s.RunID
	s.fieldMap["skill_name"] = s.SkillName
	s.fieldMap["skill_id"] = s.SkillID
	s.fieldMap["company_id"] = s.CompanyID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["api_key_id"] = s.APIKeyID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["status"] = s.Status
	s.fieldMap["params"] = s.Params
	s.fieldMap["result"] = s.Result
	s.fieldMap["artifacts"] = s.Artifacts
	s.fieldMap["progress"] = s.Progress
	s.fieldMap["error"] = s.Error
	s.fieldMap["stdout_tail"] = s.StdoutTail
	s.fieldMap["stderr_tail"] = s.StderrTail
	s.fieldMap["duration_ms"] = s.DurationMs
	s.fieldMap["attempt"] = s.Attempt
	s.fieldMap["max_attempts"] = s.MaxAttempts
	s.fieldMap["failure_kind"] = s.FailureKind
	s.fieldMap["next_retry_at"] = s.NextRetryAt
	s.fieldMap["exec_context"] = s.ExecContext
	s.fieldMap["attempts"] = s.Attempts
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["started_at"] = s.StartedAt
	s.fieldMap["finished_at"] = s.FinishedAt
}

func (s skillRun) clone(db *gorm.DB) skillRun {
	s.skillRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skillRun) replaceDB(db *gorm.DB) skillRun {
	s.skillRunDo.ReplaceDB(db)
	return s
}

type skillRunDo struct{ gen.DO }

type ISkillRunDo interface {
	gen.SubQuery
	Debug() ISkillRunDo
	WithContext(ctx context.Context) ISkillRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISkillRunDo
	WriteDB() ISkillRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISkillRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISkillRunDo
	Not(conds ...gen.Condition) ISkillRunDo
	Or(conds ...gen.Condition) ISkillRunDo
	Select(conds ...field.Expr) ISkillRunDo
	Where(conds ...gen.Condition) ISkillRunDo
	Order(conds ...field.Expr) ISkillRunDo
	Distinct(cols ...field.Expr) ISkillRunDo
	Omit(cols ...field.Expr) ISkillRunDo
	Join(table schema.Tabler, on ...field.Expr) ISkillRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISkillRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISkillRunDo
	Group(cols ...field.Expr) ISkillRunDo
	Having(conds ...gen.Condition) ISkillRunDo
	Limit(limit int) ISkillRunDo
	Offset(offset int) ISkillRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISkillRunDo
	Unscoped() ISkillRunDo
	Create(values ...*model.SkillRun) error
	CreateInBatches(values []*model.SkillRun, batchSize int) error
	Save(values ...*model.SkillRun) error
	First() (*model.SkillRun, error)
	Take() (*model.SkillRun, error)
	Last() (*model.SkillRun, error)
	Find() ([]*model.SkillRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkillRun, err error)
	FindInBatches(result *[]*model.SkillRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SkillRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISkillRunDo
	Assign(attrs ...field.AssignExpr) ISkillRunDo
	Joins(fields ...field.RelationField) ISkillRunDo
	Preload(fields ...field.RelationField) ISkillRunDo
	FirstOrInit() (*model.SkillRun, error)
	FirstOrCreate() (*model.SkillRun, error)
	FindByPage(offset int, limit int) (result []*model.SkillRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISkillRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s skillRunDo) Debug() ISkillRunDo {
	return s.withDO(s.DO.Debug())
}

func (s skillRunDo) WithContext(ctx context.Context) ISkillRunDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skillRunDo) ReadDB() ISkillRunDo {
	return s.Clauses(dbresolver.Read)
}

func (s skillRunDo) WriteDB() ISkillRunDo {
	return s.Clauses(dbresolver.Write)
}

func (s skillRunDo) Session(config *gorm.Session) ISkillRunDo {
	return s.withDO(s.DO.Session(config))
}

func (s skillRunDo) Clauses(conds ...clause.Expression) ISkillRunDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skillRunDo) Returning(value interface{}, columns ...string) ISkillRunDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skillRunDo) Not(conds ...gen.Condition) ISkillRunDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s skillRunDo) Or(conds ...gen.Condition) ISkillRunDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s skillRunDo) Select(conds ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s skillRunDo) Where(conds ...gen.Condition) ISkillRunDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s skillRunDo) Order(conds ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s skillRunDo) Distinct(cols ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skillRunDo) Omit(cols ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skillRunDo) Join(table schema.Tabler, on ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skillRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skillRunDo) RightJoin(table schema.Tabler, on ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skillRunDo) Group(cols ...field.Expr) ISkillRunDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s skillRunDo) Having(conds ...gen.Condition) ISkillRunDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s skillRunDo) Limit(limit int) ISkillRunDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s skillRunDo) Offset(offset int) ISkillRunDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s skillRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISkillRunDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skillRunDo) Unscoped() ISkillRunDo {
	return s.withDO(s.DO.Unscoped())
}

func (s skillRunDo) Create(values ...*model.SkillRun) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skillRunDo) CreateInBatches(values []*model.SkillRun, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skillRunDo) Save(values ...*model.SkillRun) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skillRunDo) First() (*model.SkillRun, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillRun), nil
	}
}

func (s skillRunDo) Take() (*model.SkillRun, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillRun), nil
	}
}

func (s skillRunDo) Last() (*model.SkillRun, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillRun), nil
	}
}

func (s skillRunDo) Find() ([]*model.SkillRun, error) {
	result, err := s.DO.Find()
	return result.([]*model.SkillRun), err
}

func (s skillRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SkillRun, err error) {
	buf := make([]*model.SkillRun, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skillRunDo) FindInBatches(result *[]*model.SkillRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skillRunDo) Attrs(attrs ...field.AssignExpr) ISkillRunDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skillRunDo) Assign(attrs ...field.AssignExpr) ISkillRunDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skillRunDo) Joins(fields ...field.RelationField) ISkillRunDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skillRunDo) Preload(fields ...field.RelationField) ISkillRunDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skillRunDo) FirstOrInit() (*model.SkillRun, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillRun), nil
	}
}

func (s skillRunDo) FirstOrCreate() (*model.SkillRun, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SkillRun), nil
	}
}

func (s skillRunDo) FindByPage(offset int, limit int) (result []*model.SkillRun, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skillRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skillRunDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skillRunDo) Delete(models ...*model.SkillRun) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skillRunDo) withDO(do gen.Dao) *skillRunDo {
	s.DO = *do.(*gen.DO)
	return s
}
