// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/dal/model"
)

func newTokenUsage(db *gorm.DB, opts ...gen.DOOption) tokenUsage {
	_tokenUsage := tokenUsage{}

	_tokenUsage.tokenUsageDo.UseDB(db, opts...)
	_tokenUsage.tokenUsageDo.UseModel(&model.TokenUsage{})

	tableName := _tokenUsage.tokenUsageDo.TableName()
	_tokenUsage.ALL = field.NewAsterisk(tableName)
	_tokenUsage.ID = field.NewInt64(tableName, "id")
	_tokenUsage.SessionID = field.NewString(tableName, "session_id")
	_tokenUsage.CompanyID = field.NewInt64(tableName, "company_id")
	_tokenUsage.UserID = field.NewInt64(tableName, "user_id")
	_tokenUsage.Model = field.NewString(tableName, "model")
	_tokenUsage.ProviderKey = field.NewString(tableName, "provider_key")
	_tokenUsage.RoundIndex = field.NewInt64(tableName, "round_index")
	_tokenUsage.Purpose = field.NewString(tableName, "purpose")
	_tokenUsage.PromptTokens = field.NewInt64(tableName, "prompt_tokens")
	_tokenUsage.CompletionTokens = field.NewInt64(tableName, "completion_tokens")
	_tokenUsage.CachedTokens = field.NewInt64(tableName, "cached_tokens")
	_tokenUsage.ReasoningTokens = field.NewInt64(tableName, "reasoning_tokens")
	_tokenUsage.CreatedAt = field.NewTime(tableName, "created_at")

	_tokenUsage.fillFieldMap()

	return _tokenUsage
}

type tokenUsage struct {
	tokenUsageDo tokenUsageDo

	ALL              field.Asterisk
	ID               field.Int64
	SessionID        field.String
	CompanyID        field.Int64
	UserID           field.Int64
	Model            field.String
	ProviderKey      field.String
	RoundIndex       field.Int64
	Purpose          field.String
	PromptTokens     field.Int64
	CompletionTokens field.Int64
	CachedTokens     field.Int64
	ReasoningTokens  field.Int64
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (t tokenUsage) Table(newTableName string) *tokenUsage {
	t.tokenUsageDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tokenUsage) As(alias string) *tokenUsage {
	t.tokenUsageDo.DO = *(t.tokenUsageDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tokenUsage) updateTableName(table string) *tokenUsage {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.SessionID = field.NewString(table, "session_id")
	t.CompanyID = field.NewInt64(table, "company_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.Model = field.NewString(table, "model")
	t.ProviderKey = field.NewString(table, "provider_key")
	t.RoundIndex = field.NewInt64(table, "round_index")
	t.Purpose = field.NewString(table, "purpose")
	t.PromptTokens = field.NewInt64(table, "prompt_tokens")
	t.CompletionTokens = field.NewInt64(table, "completion_tokens")
	t.CachedTokens = field.NewInt64(table, "cached_tokens")
	t.ReasoningTokens = field.NewInt64(table, "reasoning_tokens")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *tokenUsage) WithContext(ctx context.Context) ITokenUsageDo {
	return t.tokenUsageDo.WithContext(ctx)
}

func (t tokenUsage) TableName() string { return t.tokenUsageDo.TableName() }

func (t tokenUsage) Alias() string { return t.tokenUsageDo.Alias() }

func (t tokenUsage) Columns(cols ...field.Expr) gen.Columns { return t.tokenUsageDo.Columns(cols...) }

func (t *tokenUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tokenUsage) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["session_id"] = t.SessionID
	t.fieldMap["company_id"] = t.CompanyID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["model"] = t.Model
	t.fieldMap["provider_key"] = t.ProviderKey
	t.fieldMap["round_index"] = t.RoundIndex
	t.fieldMap["purpose"] = t.Purpose
	t.fieldMap["prompt_tokens"] = t.PromptTokens
	t.fieldMap["completion_tokens"] = t.CompletionTokens
	t.fieldMap["cached_tokens"] = t.CachedTokens
	t.fieldMap["reasoning_tokens"] = t.ReasoningTokens
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t tokenUsage) clone(db *gorm.DB) tokenUsage {
	t.tokenUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tokenUsage) replaceDB(db *gorm.DB) tokenUsage {
	t.tokenUsageDo.ReplaceDB(db)
	return t
}

type tokenUsageDo struct{ gen.DO }

type ITokenUsageDo interface {
	gen.SubQuery
	Debug() ITokenUsageDo
	WithContext(ctx context.Context) ITokenUsageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITokenUsageDo
	WriteDB() ITokenUsageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITokenUsageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITokenUsageDo
	Not(conds ...gen.Condition) ITokenUsageDo
	Or(conds ...gen.Condition) ITokenUsageDo
	Select(conds ...field.Expr) ITokenUsageDo
	Where(conds ...gen.Condition) ITokenUsageDo
	Order(conds ...field.Expr) ITokenUsageDo
	Distinct(cols ...field.Expr) ITokenUsageDo
	Omit(cols ...field.Expr) ITokenUsageDo
	Join(table schema.Tabler, on ...field.Expr) ITokenUsageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITokenUsageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITokenUsageDo
	Group(cols ...field.Expr) ITokenUsageDo
	Having(conds ...gen.Condition) ITokenUsageDo
	Limit(limit int) ITokenUsageDo
	Offset(offset int) ITokenUsageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITokenUsageDo
	Unscoped() ITokenUsageDo
	Create(values ...*model.TokenUsage) error
	CreateInBatches(values []*model.TokenUsage, batchSize int) error
	Save(values ...*model.TokenUsage) error
	First() (*model.TokenUsage, error)
	Take() (*model.TokenUsage, error)
	Last() (*model.TokenUsage, error)
	Find() ([]*model.TokenUsage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TokenUsage, err error)
	FindInBatches(result *[]*model.TokenUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TokenUsage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITokenUsageDo
	Assign(attrs ...field.AssignExpr) ITokenUsageDo
	Joins(fields ...field.RelationField) ITokenUsageDo
	Preload(fields ...field.RelationField) ITokenUsageDo
	FirstOrInit() (*model.TokenUsage, error)
	FirstOrCreate() (*model.TokenUsage, error)
	FindByPage(offset int, limit int) (result []*model.TokenUsage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITokenUsageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tokenUsageDo) Debug() ITokenUsageDo {
	return t.withDO(t.DO.Debug())
}

func (t tokenUsageDo) WithContext(ctx context.Context) ITokenUsageDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tokenUsageDo) ReadDB() ITokenUsageDo {
	return t.Clauses(dbresolver.Read)
}

func (t tokenUsageDo) WriteDB() ITokenUsageDo {
	return t.Clauses(dbresolver.Write)
}

func (t tokenUsageDo) Session(config *gorm.Session) ITokenUsageDo {
	return t.withDO(t.DO.Session(config))
}

func (t tokenUsageDo) Clauses(conds ...clause.Expression) ITokenUsageDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tokenUsageDo) Returning(value interface{}, columns ...string) ITokenUsageDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tokenUsageDo) Not(conds ...gen.Condition) ITokenUsageDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tokenUsageDo) Or(conds ...gen.Condition) ITokenUsageDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tokenUsageDo) Select(conds ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tokenUsageDo) Where(conds ...gen.Condition) ITokenUsageDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tokenUsageDo) Order(conds ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tokenUsageDo) Distinct(cols ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tokenUsageDo) Omit(cols ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tokenUsageDo) Join(table schema.Tabler, on ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tokenUsageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tokenUsageDo) RightJoin(table schema.Tabler, on ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tokenUsageDo) Group(cols ...field.Expr) ITokenUsageDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tokenUsageDo) Having(conds ...gen.Condition) ITokenUsageDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tokenUsageDo) Limit(limit int) ITokenUsageDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tokenUsageDo) Offset(offset int) ITokenUsageDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tokenUsageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITokenUsageDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tokenUsageDo) Unscoped() ITokenUsageDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tokenUsageDo) Create(values ...*model.TokenUsage) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tokenUsageDo) CreateInBatches(values []*model.TokenUsage, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tokenUsageDo) Save(values ...*model.TokenUsage) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tokenUsageDo) First() (*model.TokenUsage, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenUsage), nil
	}
}

func (t tokenUsageDo) Take() (*model.TokenUsage, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenUsage), nil
	}
}

func (t tokenUsageDo) Last() (*model.TokenUsage, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenUsage), nil
	}
}

func (t tokenUsageDo) Find() ([]*model.TokenUsage, error) {
	result, err := t.DO.Find()
	return result.([]*model.TokenUsage), err
}

func (t tokenUsageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TokenUsage, err error) {
	buf := make([]*model.TokenUsage, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tokenUsageDo) FindInBatches(result *[]*model.TokenUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tokenUsageDo) Attrs(attrs ...field.AssignExpr) ITokenUsageDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tokenUsageDo) Assign(attrs ...field.AssignExpr) ITokenUsageDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tokenUsageDo) Joins(fields ...field.RelationField) ITokenUsageDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tokenUsageDo) Preload(fields ...field.RelationField) ITokenUsageDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tokenUsageDo) FirstOrInit() (*model.TokenUsage, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenUsage), nil
	}
}

func (t tokenUsageDo) FirstOrCreate() (*model.TokenUsage, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenUsage), nil
	}
}

func (t tokenUsageDo) FindByPage(offset int, limit int) (result []*model.TokenUsage, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tokenUsageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tokenUsageDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tokenUsageDo) Delete(models ...*model.TokenUsage) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tokenUsageDo) withDO(do gen.Dao) *tokenUsageDo {
	t.DO = *do.(*gen.DO)
	return t
}
